package com.mco.wackyguesses.entities.dorito;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.math.MathHelper;

/**
 * Mr Senor Dorito - TheMinecraftOverlord
 * Created using Tabula 4.1.1
 */
public class ModelDorito extends ModelBase {
    public ModelRenderer ChipA;
    public ModelRenderer ChipB;
    public ModelRenderer ChipC;
    public ModelRenderer ChipD;
    public ModelRenderer ChipE;
    public ModelRenderer ChipF;
    public ModelRenderer ChipG;
    public ModelRenderer ChipH;
    public ModelRenderer ChipI;
    public ModelRenderer ChipJ;
    public ModelRenderer ChipK;
    public ModelRenderer ChipL;
    public ModelRenderer ChipM;
    public ModelRenderer ChipN;
    public ModelRenderer ChipO;
    public ModelRenderer ChipP;
    public ModelRenderer ChipQ;
    public ModelRenderer ChipR;
    public ModelRenderer ChipS;
    public ModelRenderer ChipT;
    public ModelRenderer ChipU;
    public ModelRenderer ChipV;
    public ModelRenderer ChipW;
    public ModelRenderer ChipX;
    public ModelRenderer ChipY;
    public ModelRenderer ChipZ;
    public ModelRenderer ChipAA;
    public ModelRenderer ChipAB;
    public ModelRenderer ChipAC;
    public ModelRenderer ChipAD;
    public ModelRenderer ChipAE;
    public ModelRenderer SombreroA;
    public ModelRenderer EyeL;
    public ModelRenderer EyeR;
    public ModelRenderer Mouth;
    public ModelRenderer LArmA;
    public ModelRenderer RArmA;
    public ModelRenderer LLeg;
    public ModelRenderer RLeg;
    public ModelRenderer SombreroB;
    public ModelRenderer SombreroC;
    public ModelRenderer SombreroD;
    public ModelRenderer SombreroE;
    public ModelRenderer SombreroF;
    public ModelRenderer SombreroG;
    public ModelRenderer SombreroH;
    public ModelRenderer SombreroI;
    public ModelRenderer SombreroJ;
    public ModelRenderer SombreroK;
    public ModelRenderer SombreroL;
    public ModelRenderer SombreroBase;
    public ModelRenderer SombreroBase1;
    public ModelRenderer SombreroBase3;
    public ModelRenderer SombreroBase2;
    public ModelRenderer SombreroBase4;
    public ModelRenderer SombreroBase5;
    public ModelRenderer SombreroBase6;
    public ModelRenderer SombreroTopA;
    public ModelRenderer SombreroTopB;
    public ModelRenderer SombreroTopC;
    public ModelRenderer SombreroTopD;
    public ModelRenderer SombreroTopE;
    public ModelRenderer SombreroTopF;
    public ModelRenderer SombreroTopG;
    public ModelRenderer SombreroTopH;
    public ModelRenderer SombreroTopI;
    public ModelRenderer LArmA_1;
    public ModelRenderer RArmB;

    public ModelDorito() {
        this.textureWidth = 128;
        this.textureHeight = 128;
        this.ChipW = new ModelRenderer(this, 0, 0);
        this.ChipW.setRotationPoint(-5.9F, 10.0F, 0.0F);
        this.ChipW.addBox(0.0F, 0.0F, 0.0F, 10, 1, 1, 0.0F);
        this.RLeg = new ModelRenderer(this, 20, 85);
        this.RLeg.setRotationPoint(0.6F, 17.0F, 0.0F);
        this.RLeg.addBox(0.0F, 0.0F, 0.0F, 1, 7, 1, 0.0F);
        this.ChipQ = new ModelRenderer(this, 0, 0);
        this.ChipQ.setRotationPoint(-8.6F, 4.0F, 0.0F);
        this.ChipQ.addBox(0.0F, 0.0F, 0.0F, 16, 1, 1, 0.0F);
        this.SombreroBase5 = new ModelRenderer(this, 0, 38);
        this.SombreroBase5.setRotationPoint(-5.0F, 3.0F, 12.0F);
        this.SombreroBase5.addBox(15.0F, 0.0F, 6.0F, 3, 1, 3, 0.0F);
        this.SombreroTopE = new ModelRenderer(this, 0, 75);
        this.SombreroTopE.setRotationPoint(2.5F, -4.5F, 20.0F);
        this.SombreroTopE.addBox(0.0F, -1.0F, -9.0F, 2, 2, 2, 0.0F);
        this.SombreroTopH = new ModelRenderer(this, 0, 100);
        this.SombreroTopH.setRotationPoint(0.0F, -1.0F, 19.0F);
        this.SombreroTopH.addBox(0.0F, -1.0F, -9.0F, 7, 3, 4, 0.0F);
        this.SombreroTopG = new ModelRenderer(this, 0, 92);
        this.SombreroTopG.setRotationPoint(-1.0F, -4.0F, 22.0F);
        this.SombreroTopG.addBox(2.0F, -1.0F, -11.0F, 5, 3, 2, 0.0F);
        this.SombreroK = new ModelRenderer(this, 0, 17);
        this.SombreroK.setRotationPoint(-8.8F, 0.0F, 8.9F);
        this.SombreroK.addBox(0.0F, 0.0F, -1.0F, 7, 4, 2, 0.0F);
        this.setRotateAngle(SombreroK, 0.0F, -5.235987755982989F, 0.0F);
        this.ChipK = new ModelRenderer(this, 0, 0);
        this.ChipK.setRotationPoint(-11.8F, -2.0F, 0.0F);
        this.ChipK.addBox(0.0F, 0.0F, 0.0F, 23, 1, 1, 0.0F);
        this.ChipT = new ModelRenderer(this, 0, 0);
        this.ChipT.setRotationPoint(-7.3F, 7.0F, 0.0F);
        this.ChipT.addBox(0.0F, 0.0F, 0.0F, 13, 1, 1, 0.0F);
        this.SombreroBase6 = new ModelRenderer(this, 0, 38);
        this.SombreroBase6.setRotationPoint(-21.0F, 3.0F, 12.0F);
        this.SombreroBase6.addBox(15.0F, 0.0F, 6.0F, 3, 1, 3, 0.0F);
        this.ChipAB = new ModelRenderer(this, 0, 0);
        this.ChipAB.setRotationPoint(-3.7F, 15.0F, 0.0F);
        this.ChipAB.addBox(0.0F, 0.0F, 0.0F, 5, 1, 1, 0.0F);
        this.SombreroF = new ModelRenderer(this, 0, 17);
        this.SombreroF.setRotationPoint(12.6F, 0.0F, 20.7F);
        this.SombreroF.addBox(0.0F, 0.0F, -1.0F, 7, 4, 2, 0.0F);
        this.setRotateAngle(SombreroF, 0.0F, -2.6179938779914944F, 0.0F);
        this.SombreroBase2 = new ModelRenderer(this, 0, 38);
        this.SombreroBase2.setRotationPoint(-5.0F, 3.0F, -3.0F);
        this.SombreroBase2.addBox(15.0F, 0.0F, 6.0F, 3, 1, 3, 0.0F);
        this.SombreroBase3 = new ModelRenderer(this, 0, 38);
        this.SombreroBase3.setRotationPoint(-21.0F, 3.0F, -3.0F);
        this.SombreroBase3.addBox(15.0F, 0.0F, 6.0F, 3, 1, 3, 0.0F);
        this.SombreroBase1 = new ModelRenderer(this, 0, 43);
        this.SombreroBase1.setRotationPoint(-8.0F, 3.0F, -3.0F);
        this.SombreroBase1.addBox(5.0F, 0.0F, 4.0F, 13, 1, 5, 0.0F);
        this.SombreroD = new ModelRenderer(this, 0, 17);
        this.SombreroD.setRotationPoint(15.6F, 0.0F, 8.6F);
        this.SombreroD.addBox(0.0F, 0.0F, -1.0F, 7, 4, 2, 0.0F);
        this.setRotateAngle(SombreroD, 0.0F, -1.5707963267948966F, 0.0F);
        this.RArmB = new ModelRenderer(this, 20, 85);
        this.RArmB.setRotationPoint(0.7F, -10.5F, 0.0F);
        this.RArmB.addBox(0.0F, -10.0F, 0.0F, 1, 11, 1, 0.0F);
        this.setRotateAngle(RArmB, 0.0F, 0.0F, 1.051735407251783F);
        this.ChipP = new ModelRenderer(this, 0, 0);
        this.ChipP.setRotationPoint(-9.1F, 3.0F, 0.0F);
        this.ChipP.addBox(0.0F, 0.0F, 0.0F, 17, 1, 1, 0.0F);
        this.SombreroTopF = new ModelRenderer(this, 0, 82);
        this.SombreroTopF.setRotationPoint(0.5F, -4.0F, 20.5F);
        this.SombreroTopF.addBox(2.0F, -1.0F, -11.0F, 2, 3, 5, 0.0F);
        this.EyeR = new ModelRenderer(this, 20, 65);
        this.EyeR.setRotationPoint(-4.0F, -7.0F, -1.0F);
        this.EyeR.addBox(-6.0F, 0.0F, 0.0F, 7, 7, 0, 0.0F);
        this.ChipN = new ModelRenderer(this, 0, 0);
        this.ChipN.setRotationPoint(-10.5F, 1.0F, 0.0F);
        this.ChipN.addBox(0.0F, 0.0F, 0.0F, 20, 1, 1, 0.0F);
        this.EyeL = new ModelRenderer(this, 20, 65);
        this.EyeL.mirror = true;
        this.EyeL.setRotationPoint(8.0F, -7.0F, -1.0F);
        this.EyeL.addBox(-6.0F, 0.0F, 0.0F, 7, 7, 0, 0.0F);
        this.ChipB = new ModelRenderer(this, 0, 0);
        this.ChipB.setRotationPoint(-15.2F, -10.0F, 0.0F);
        this.ChipB.addBox(0.0F, 0.0F, 0.0F, 33, 1, 1, 0.0F);
        this.setRotateAngle(ChipB, 0.0F, 0.0F, 1.121897643181955F);
        this.ChipX = new ModelRenderer(this, 0, 0);
        this.ChipX.setRotationPoint(-5.5F, 11.0F, 0.0F);
        this.ChipX.addBox(0.0F, 0.0F, 0.0F, 9, 1, 1, 0.0F);
        this.ChipR = new ModelRenderer(this, 0, 0);
        this.ChipR.setRotationPoint(-8.3F, 5.0F, 0.0F);
        this.ChipR.addBox(0.0F, 0.0F, 0.0F, 15, 1, 1, 0.0F);
        this.SombreroTopC = new ModelRenderer(this, 38, 40);
        this.SombreroTopC.setRotationPoint(0.5F, -1.0F, 18.0F);
        this.SombreroTopC.addBox(0.0F, -1.0F, -9.0F, 6, 3, 6, 0.0F);
        this.ChipC = new ModelRenderer(this, 0, 0);
        this.ChipC.setRotationPoint(15.9F, -9.0F, 0.0F);
        this.ChipC.addBox(0.0F, 0.0F, 0.0F, 34, 1, 1, 0.0F);
        this.setRotateAngle(ChipC, 0.0F, 0.0F, 2.0943951023931953F);
        this.SombreroTopI = new ModelRenderer(this, 0, 110);
        this.SombreroTopI.setRotationPoint(1.5F, -1.0F, 18.0F);
        this.SombreroTopI.addBox(0.0F, -1.0F, -9.0F, 4, 3, 7, 0.0F);
        this.SombreroTopB = new ModelRenderer(this, 22, 8);
        this.SombreroTopB.setRotationPoint(-1.5F, 0.0F, 16.0F);
        this.SombreroTopB.addBox(0.0F, 1.0F, -9.0F, 10, 1, 10, 0.0F);
        this.SombreroL = new ModelRenderer(this, 0, 17);
        this.SombreroL.setRotationPoint(-5.7F, 0.0F, 3.3F);
        this.SombreroL.addBox(0.0F, 0.0F, -1.0F, 7, 4, 2, 0.0F);
        this.setRotateAngle(SombreroL, 0.0F, -5.759586531581287F, 0.0F);
        this.ChipA = new ModelRenderer(this, 0, 0);
        this.ChipA.setRotationPoint(-16.0F, -10.0F, 0.0F);
        this.ChipA.addBox(0.0F, 0.0F, 0.0F, 32, 1, 1, 0.0F);
        this.ChipAC = new ModelRenderer(this, 0, 0);
        this.ChipAC.setRotationPoint(-3.2F, 16.0F, 0.0F);
        this.ChipAC.addBox(0.0F, 0.0F, 0.0F, 4, 1, 1, 0.0F);
        this.ChipD = new ModelRenderer(this, 0, 0);
        this.ChipD.setRotationPoint(-15.0F, -9.0F, 0.0F);
        this.ChipD.addBox(0.0F, 0.0F, 0.0F, 30, 1, 1, 0.0F);
        this.Mouth = new ModelRenderer(this, 20, 75);
        this.Mouth.setRotationPoint(3.5F, 2.0F, -1.0F);
        this.Mouth.addBox(-9.0F, 0.0F, 0.0F, 10, 7, 0, 0.0F);
        this.ChipV = new ModelRenderer(this, 0, 0);
        this.ChipV.setRotationPoint(-6.3F, 9.0F, 0.0F);
        this.ChipV.addBox(0.0F, 0.0F, 0.0F, 11, 1, 1, 0.0F);
        this.ChipS = new ModelRenderer(this, 0, 0);
        this.ChipS.setRotationPoint(-7.7F, 6.0F, 0.0F);
        this.ChipS.addBox(0.0F, 0.0F, 0.0F, 14, 1, 1, 0.0F);
        this.LArmA = new ModelRenderer(this, 20, 85);
        this.LArmA.setRotationPoint(-12.0F, 1.0F, 0.0F);
        this.LArmA.addBox(0.0F, -10.0F, 0.0F, 1, 11, 1, 0.0F);
        this.setRotateAngle(LArmA, 0.0F, 0.0F, -2.090904443889207F);
        this.LLeg = new ModelRenderer(this, 20, 85);
        this.LLeg.setRotationPoint(-4.0F, 17.0F, 0.0F);
        this.LLeg.addBox(0.0F, 0.0F, 0.0F, 1, 7, 1, 0.0F);
        this.SombreroBase4 = new ModelRenderer(this, 0, 43);
        this.SombreroBase4.setRotationPoint(-8.0F, 3.0F, 14.0F);
        this.SombreroBase4.addBox(5.0F, 0.0F, 4.0F, 13, 1, 5, 0.0F);
        this.ChipAD = new ModelRenderer(this, 0, 0);
        this.ChipAD.setRotationPoint(-2.7F, 17.0F, 0.0F);
        this.ChipAD.addBox(0.0F, 0.0F, 0.0F, 3, 1, 1, 0.0F);
        this.SombreroTopA = new ModelRenderer(this, 7, 21);
        this.SombreroTopA.setRotationPoint(-3.5F, 1.0F, 14.0F);
        this.SombreroTopA.addBox(0.0F, 1.0F, -9.0F, 14, 1, 14, 0.0F);
        this.SombreroTopD = new ModelRenderer(this, 0, 65);
        this.SombreroTopD.setRotationPoint(1.5F, -4.0F, 19.0F);
        this.SombreroTopD.addBox(0.0F, -1.0F, -9.0F, 4, 3, 4, 0.0F);
        this.SombreroG = new ModelRenderer(this, 0, 17);
        this.SombreroG.setRotationPoint(7.0F, 0.0F, 24.1F);
        this.SombreroG.addBox(0.0F, 0.0F, -1.0F, 7, 4, 2, 0.0F);
        this.setRotateAngle(SombreroG, 0.0F, -3.141592653589793F, 0.0F);
        this.ChipU = new ModelRenderer(this, 0, 0);
        this.ChipU.setRotationPoint(-6.8F, 8.0F, 0.0F);
        this.ChipU.addBox(0.0F, 0.0F, 0.0F, 12, 1, 1, 0.0F);
        this.SombreroC = new ModelRenderer(this, 0, 17);
        this.SombreroC.setRotationPoint(12.2F, 0.0F, 3.1F);
        this.SombreroC.addBox(0.0F, 0.0F, -1.0F, 7, 4, 2, 0.0F);
        this.setRotateAngle(SombreroC, 0.0F, -1.0471975511965976F, 0.0F);
        this.ChipE = new ModelRenderer(this, 0, 0);
        this.ChipE.setRotationPoint(-14.5F, -8.0F, 0.0F);
        this.ChipE.addBox(0.0F, 0.0F, 0.0F, 29, 1, 1, 0.0F);
        this.ChipZ = new ModelRenderer(this, 0, 0);
        this.ChipZ.setRotationPoint(-4.6F, 13.0F, 0.0F);
        this.ChipZ.addBox(0.0F, 0.0F, 0.0F, 7, 1, 1, 0.0F);
        this.SombreroI = new ModelRenderer(this, 0, 17);
        this.SombreroI.setRotationPoint(-5.2F, 0.0F, 21.1F);
        this.SombreroI.addBox(0.0F, 0.0F, -1.0F, 7, 4, 2, 0.0F);
        this.setRotateAngle(SombreroI, 0.0F, -4.1887902047863905F, 0.0F);
        this.ChipY = new ModelRenderer(this, 0, 0);
        this.ChipY.setRotationPoint(-5.0F, 12.0F, 0.0F);
        this.ChipY.addBox(0.0F, 0.0F, 0.0F, 8, 1, 1, 0.0F);
        this.ChipAA = new ModelRenderer(this, 0, 0);
        this.ChipAA.setRotationPoint(-4.1F, 14.0F, 0.0F);
        this.ChipAA.addBox(0.0F, 0.0F, 0.0F, 6, 1, 1, 0.0F);
        this.RArmA = new ModelRenderer(this, 20, 85);
        this.RArmA.setRotationPoint(11.0F, 1.0F, 0.0F);
        this.RArmA.addBox(0.0F, -10.0F, 0.0F, 1, 11, 1, 0.0F);
        this.setRotateAngle(RArmA, 0.0F, 0.0F, 2.090904443889207F);
        this.ChipF = new ModelRenderer(this, 0, 0);
        this.ChipF.setRotationPoint(-14.0F, -7.0F, 0.0F);
        this.ChipF.addBox(0.0F, 0.0F, 0.0F, 28, 1, 1, 0.0F);
        this.ChipH = new ModelRenderer(this, 0, 0);
        this.ChipH.setRotationPoint(-13.0F, -5.0F, 0.0F);
        this.ChipH.addBox(0.0F, 0.0F, 0.0F, 26, 1, 1, 0.0F);
        this.SombreroBase = new ModelRenderer(this, 0, 50);
        this.SombreroBase.setRotationPoint(-8.0F, 3.0F, 9.0F);
        this.SombreroBase.addBox(0.0F, 0.0F, -3.0F, 23, 1, 12, 0.0F);
        this.ChipJ = new ModelRenderer(this, 0, 0);
        this.ChipJ.setRotationPoint(-12.3F, -3.0F, 0.0F);
        this.ChipJ.addBox(0.0F, 0.0F, 0.0F, 24, 1, 1, 0.0F);
        this.SombreroE = new ModelRenderer(this, 0, 17);
        this.SombreroE.setRotationPoint(15.7F, 0.0F, 15.1F);
        this.SombreroE.addBox(0.0F, 0.0F, -1.0F, 7, 4, 2, 0.0F);
        this.setRotateAngle(SombreroE, 0.0F, -2.0943951023931953F, 0.0F);
        this.ChipG = new ModelRenderer(this, 0, 0);
        this.ChipG.setRotationPoint(-13.5F, -6.0F, 0.0F);
        this.ChipG.addBox(0.0F, 0.0F, 0.0F, 27, 1, 1, 0.0F);
        this.ChipI = new ModelRenderer(this, 0, 0);
        this.ChipI.setRotationPoint(-12.9F, -4.0F, 0.0F);
        this.ChipI.addBox(0.0F, 0.0F, 0.0F, 25, 1, 1, 0.0F);
        this.ChipM = new ModelRenderer(this, 0, 0);
        this.ChipM.setRotationPoint(-11.0F, 0.0F, 0.0F);
        this.ChipM.addBox(0.0F, 0.0F, 0.0F, 21, 1, 1, 0.0F);
        this.ChipO = new ModelRenderer(this, 0, 0);
        this.ChipO.setRotationPoint(-9.6F, 2.0F, 0.0F);
        this.ChipO.addBox(0.0F, 0.0F, 0.0F, 18, 1, 1, 0.0F);
        this.ChipAE = new ModelRenderer(this, 0, 0);
        this.ChipAE.setRotationPoint(-1.7F, 18.0F, 0.0F);
        this.ChipAE.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1, 0.0F);
        this.SombreroH = new ModelRenderer(this, 0, 17);
        this.SombreroH.setRotationPoint(0.5F, 0.0F, 24.2F);
        this.SombreroH.addBox(0.0F, 0.0F, -1.0F, 7, 4, 2, 0.0F);
        this.setRotateAngle(SombreroH, 0.0F, -3.6651914291880923F, 0.0F);
        this.SombreroA = new ModelRenderer(this, 0, 17);
        this.SombreroA.setRotationPoint(-3.5F, -14.0F, -11.0F);
        this.SombreroA.addBox(0.0F, 0.0F, -1.0F, 7, 4, 2, 0.0F);
        this.ChipL = new ModelRenderer(this, 0, 0);
        this.ChipL.setRotationPoint(-11.4F, -1.0F, 0.0F);
        this.ChipL.addBox(0.0F, 0.0F, 0.0F, 22, 1, 1, 0.0F);
        this.SombreroJ = new ModelRenderer(this, 0, 17);
        this.SombreroJ.setRotationPoint(-8.6F, 0.0F, 15.4F);
        this.SombreroJ.addBox(0.0F, 0.0F, -1.0F, 7, 4, 2, 0.0F);
        this.setRotateAngle(SombreroJ, 0.0F, -4.71238898038469F, 0.0F);
        this.SombreroB = new ModelRenderer(this, 0, 17);
        this.SombreroB.mirror = true;
        this.SombreroB.setRotationPoint(6.5F, 0.0F, -0.1F);
        this.SombreroB.addBox(0.0F, 0.0F, -1.0F, 7, 4, 2, 0.0F);
        this.setRotateAngle(SombreroB, 0.0F, -0.5235987755982988F, 0.0F);
        this.LArmA_1 = new ModelRenderer(this, 20, 85);
        this.LArmA_1.setRotationPoint(-0.3F, -9.5F, 0.0F);
        this.LArmA_1.addBox(0.0F, -10.0F, 0.0F, 1, 11, 1, 0.0F);
        this.setRotateAngle(LArmA_1, 0.0F, 0.0F, -1.051735407251783F);
        this.SombreroA.addChild(this.SombreroBase5);
        this.SombreroA.addChild(this.SombreroTopE);
        this.SombreroA.addChild(this.SombreroTopH);
        this.SombreroA.addChild(this.SombreroTopG);
        this.SombreroA.addChild(this.SombreroK);
        this.SombreroA.addChild(this.SombreroBase6);
        this.SombreroA.addChild(this.SombreroF);
        this.SombreroA.addChild(this.SombreroBase2);
        this.SombreroA.addChild(this.SombreroBase3);
        this.SombreroA.addChild(this.SombreroBase1);
        this.SombreroA.addChild(this.SombreroD);
        this.RArmA.addChild(this.RArmB);
        this.SombreroA.addChild(this.SombreroTopF);
        this.SombreroA.addChild(this.SombreroTopC);
        this.SombreroA.addChild(this.SombreroTopI);
        this.SombreroA.addChild(this.SombreroTopB);
        this.SombreroA.addChild(this.SombreroL);
        this.SombreroA.addChild(this.SombreroBase4);
        this.SombreroA.addChild(this.SombreroTopA);
        this.SombreroA.addChild(this.SombreroTopD);
        this.SombreroA.addChild(this.SombreroG);
        this.SombreroA.addChild(this.SombreroC);
        this.SombreroA.addChild(this.SombreroI);
        this.SombreroA.addChild(this.SombreroBase);
        this.SombreroA.addChild(this.SombreroE);
        this.SombreroA.addChild(this.SombreroH);
        this.SombreroA.addChild(this.SombreroJ);
        this.SombreroA.addChild(this.SombreroB);
        this.LArmA.addChild(this.LArmA_1);
    }

    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) { 
        this.ChipW.render(f5);
        this.RLeg.render(f5);
        this.ChipQ.render(f5);
        this.ChipK.render(f5);
        this.ChipT.render(f5);
        this.ChipAB.render(f5);
        this.ChipP.render(f5);
        this.EyeR.render(f5);
        this.ChipN.render(f5);
        this.EyeL.render(f5);
        this.ChipB.render(f5);
        this.ChipX.render(f5);
        this.ChipR.render(f5);
        this.ChipC.render(f5);
        this.ChipA.render(f5);
        this.ChipAC.render(f5);
        this.ChipD.render(f5);
        this.Mouth.render(f5);
        this.ChipV.render(f5);
        this.ChipS.render(f5);
        this.LArmA.render(f5);
        this.LLeg.render(f5);
        this.ChipAD.render(f5);
        this.ChipU.render(f5);
        this.ChipE.render(f5);
        this.ChipZ.render(f5);
        this.ChipY.render(f5);
        this.ChipAA.render(f5);
        this.RArmA.render(f5);
        this.ChipF.render(f5);
        this.ChipH.render(f5);
        this.ChipJ.render(f5);
        this.ChipG.render(f5);
        this.ChipI.render(f5);
        this.ChipM.render(f5);
        this.ChipO.render(f5);
        this.ChipAE.render(f5);
        this.SombreroA.render(f5);
        this.ChipL.render(f5);
    }

    /**
     * This is a helper function from Tabula to set the rotation of model parts
     */
    public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
        modelRenderer.rotateAngleX = x;
        modelRenderer.rotateAngleY = y;
        modelRenderer.rotateAngleZ = z;
    }

    /**
     * Sets the model's various rotation angles. For bipeds, par1 and par2 are used for animating the movement of arms
     * and legs, where par1 represents the time(so that arms and legs swing back and forth) and par2 represents how
     * "far" arms and legs can swing at most.
     */
    public void setRotationAngles(float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch, float scaleFactor, Entity entityIn)
    {
        this.LLeg.rotateAngleX = MathHelper.cos(limbSwing * 0.6662F) * 1.4F * limbSwingAmount;
        this.RArmB.rotateAngleY = MathHelper.cos(limbSwing * 0.8662F) * 1.4F * limbSwingAmount;
        this.RLeg.rotateAngleX = MathHelper.cos(limbSwing * 0.6662F + (float)Math.PI) * 1.4F * limbSwingAmount;
        this.LArmA_1.rotateAngleY = MathHelper.cos(limbSwing * -0.8662F + (float)Math.PI) * 1.4F * limbSwingAmount;
    }

}
